       IDENTIFICATION DIVISION.
       PROGRAM-ID. maxi.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
            DISPLAY function max(12 37 373 27973 439938)
            STOP RUN.
       END PROGRAM maxi.